version: "3.1"
services:
  api:
    # When you done development then push the image to the docker hub instead of build and use the image from there
    image: ehtelahi/fastapi
    depends_on:
      - postgres
    ports:
      - '80:8000'
    env_file:
      - ./.env
    environment:
      DATABASE_HOSTNAME: ${DATABASE_NAME}
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - dev

  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  postgres_data:

networks:
  dev: