"""init 3

Revision ID: 6dec1e520d85
Revises: 7d60a6f66591
Create Date: 2024-03-21 04:34:00.415886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dec1e520d85'
down_revision: Union[str, None] = '7d60a6f66591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.drop_column('users', 'phone_number_1')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number_1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
