"""init 2

Revision ID: 7d60a6f66591
Revises: d57642a212fc
Create Date: 2024-03-21 04:31:51.276746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d60a6f66591'
down_revision: Union[str, None] = 'd57642a212fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number_1', sa.String(), nullable=True))
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'phone_number_1')
    # ### end Alembic commands ###
